# STAT 440 Statistical Data Management - Fall 2021
## Week15 Lab03 Wed
### Only the driver should submit this assignment into their individual student repo. Save the filename as lab03-week15-wed-netID.Rmd (or .ipynb for Python users). Then render this file to .html when completed. 
#### Both .Rmd/.ipynb and .html files must be submitted by 11:00 am. Any lab submitted after 11:00 am will be deducted 1 point for being late.

**#1** Using Markdown syntax, make a non-numbered list with the names of everyone at your station in all caps. Your name should appear in all lower case text.

-  Jonathan Kang  
-  

**#2** statement: **Data analysts** have a strong background in data analysis, statistical theory, and communication.

If the text in bold is the term that makes the statement true, then write TRUE below in all caps. If the text in bold is the term that makes the statement false, then write FALSE below in all caps and write the correct term in bold text in a new line under FALSE.

**#3** Import the following dataset using a programming language and its corresponding data URL. Ensure the Date Reported and Time Reported columns get properly formatted to datetime and time formats, respectively. Read the data descriptions to help verify the import was successful.

- University of Illinois Daily Crime Log and its GHE data URL https://github-dev.cs.illinois.edu/stat440-fa21/stat440-fa21-course-content/raw/master/data/daily-crime-log-data.csv or Box data URL https://uofi.box.com/shared/static/7uah46fdogn8gdc1zy06efuxsfpqif4g.csv

- The dataset (.csv file) contains 462 legitimate observations and 8 columns. The observations are crimes reported in the University area within the last 60 days. Instructions for interpreting the data is in its [data key](https://police.illinois.edu/wp-content/uploads/2016/02/Crime-Log-Instructions.pdf). **Do not worry about getting the legitimate number of observations in this problem. This will get resolved in the next problem.**

**#4** Validate and clean the following errors that may be present in the data:

errors | resolution |
---|---|
the column names appear within the data observations | remove those rows |
Date occurred equals FALL 2021 | remove those rows and reformat the column to be date or datetime format |
Time occurred equals UNKNOWN and reformat the column to be hms or datetime format | remove those rows |
general location contains a forward slash | change forward slashes to the string ' AND ' such that there is a space before and after the word 'AND'
crime descriptions for THEFT \$500 AND UNDER is equivalent to THEFT UNDER \$500 | make these two crime descriptions into one description called THEFT \$500 AND UNDER |
disposition ADMIN CLOSED is equivalent to ADMIN. CLOSE | make these two dispositions into one disposition called ADMIN. CLOSED |
disposition STUDENT DISC REFERRAL is equivalent to STUDENT DISCIPLINE REFERRAL | make these two dispositions into one disposition called STUDENT DISCIPLINE REFERRAL |

**For the \$500, the backslash does not need to be included in the string manipulation.**

**#5** Using the validated and cleaned data resulting from **Problem 4**, how many reported crimes involve drugs or alcohol and are not dispositioned as reported to other agency nor referred to other jurisdiction?

